# Generated by Django 4.1.3 on 2023-03-04 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150)),
                ('meaning', models.CharField(max_length=300)),
                ('created', models.DateField(default=datetime.date(2023, 3, 4))),
                ('example', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
