# Generated by Django 4.1.3 on 2023-08-07 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='created',
            field=models.DateField(default=datetime.date(2023, 8, 7)),
        ),
    ]
