# Generated by Django 4.1.3 on 2023-08-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_dictionary_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='chat_id',
            field=models.PositiveIntegerField(default=764719178),
        ),
    ]
